name: Build and Deploy to Azure App Service (Manual Credentials)

on:
  push:
    branches:
      - main # Hoặc nhánh chính của bạn
  workflow_dispatch:

env:
  ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}
  WEBAPP_NAME: ${{ secrets.AZURE_APP_NAME }}
  IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
  # Không cần AZURE_RESOURCE_GROUP ở đây vì publish profile đã chứa thông tin đó

jobs:
  build_and_push_to_acr:
    name: Build and Push Docker Image to ACR
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # Giả định model/artifacts đã có trong repo (Cách 1)
    # Nếu bạn muốn chạy run_pipeline.py trong workflow, bỏ comment phần dưới
    # và đảm bảo run_pipeline.py không cần tương tác với Azure ML SDK
    # - name: Set up Python
    #   uses: actions/setup-python@v4
    #   with:
    #     python-version: '3.11'
    # - name: Install Python dependencies
    #   run: pip install -r requirements.txt
    # - name: Run training pipeline to generate artifacts
    #   run: python run_pipeline.py

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.ACR_LOGIN_SERVER }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and push Docker image to ACR
      run: |
        docker build . -t ${{ env.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
        docker build . -t ${{ env.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:latest
        docker push ${{ env.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
        docker push ${{ env.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:latest

  deploy_to_app_service:
    name: Deploy Image to Azure App Service
    runs-on: ubuntu-latest
    needs: build_and_push_to_acr

    steps:
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: '${{ env.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ github.sha }}'
        # Nếu bạn muốn luôn deploy tag 'latest':
        # images: '${{ env.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:latest'